on: 
  workflow_dispatch
jobs:
  job_1:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node_version: [x14, x15, x16]

    runs-on: ${{ strategy.os }}

    steps:
        -  name: running os against versions
           uses: actions/setup-node@v3.6.0
           with:
             node-version: ${{ strategy.node_version }}
